# Complete Manifest Where in single yml we defined Deployment & Service for SpringApp & PVC(with default  StorageClass),ReplicaSet & Service For Mongo.
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gateway
  name: webapp deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp_contianer
          image: 322266404742.dkr.ecr.us-west-2.amazonaws.com/webapp:1.0.0
          ports:
            - containerPort: 8080
