apiVersion: v1
kind: Secret
metadata:
  name: fusisoft-secret
  namespace: gateway
type: Opaque
data:
  ADMIN_EMAIL: ZnVzaXNvZnRAZ21haWwuY29t # Base64 of 'fusisoft@gmail.com'
  ADMIN_PASSWORD: U2NoMDBsQDEy # Base64 of 'Sch00l@12'
  DB_PASSWORD: K3hoWlNNMy1+dVgyclhpQ2lXUUliflZbRjRfbQ== # Base64 of 'your_password'
